name: Go

on:
  push:
    branches: [ master, "masquerade_exception_list" ]

  pull_request:
    branches: [ master ]

env:
  REGISTRY: tsuru/ip-masq-agent
  BIN_OS: linux
  BIN_ARCH: amd64
  BIN: ip-masq-agent
  BASEIMAGE: k8s.gcr.io/build-image/distroless-iptables:v0.1.1

jobs:

  test:
    name: Test 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1
    - run: make test

  publish:
    name: Build and Publish container images
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - name: Build binary
      run: |
        make all
        sed \
          -e "s|{ARG_BIN}|${BIN}|g" \
          -e "s|{ARG_ARCH}|${BIN_ARCH}|g" \
          -e "s|{ARG_OS}|${BIN_OS}|g" \
          -e "s|{ARG_FROM}|${BASEIMAGE}|g" \
          Dockerfile.in > Dockerfile
        cp ${BIN} ${BIN}-${BIN_OS}-${BIN_ARCH}
        cp -r bin/linux_amd64/ip-masq-agent /tmp/.buildx-cache
    - uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        push: false
        build-args: |
          ARCH=amd64
        tags: |
          tsuru/ip-masq-agent:latest
          tsuru/ip-masq-agent:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache